config/routes.rb
BlogBase::Application.routes.draw do
  devise_for :users, 
             path_names: {sign_up: "register"} # defaults the sign_up path to use register instead

  root to: "pages#home", 
       via: :get

  namespace :blog do

    root to: "posts#index", via: :get

    get "/page/:page" => "posts#index", 
          as: :page

    get "/posts(/tag/:tag)(/category/:category)(/page/:page)" => "posts#search", 
          as: :posts_search, 
          defaults: {page: 1}

    get "/feed" => "posts#feed",
          as: :feed,
          defaults: {format: 'atom'}

    get "/rss" => redirect("/blog/feed")

    get "/atom" => redirect("/blog/feed")

    get "/:slug(/comment(/reply/:reply_id)(:comment_id))(/page/:page)" => "posts#show", 
          as: :post

    post "/comments/create" => "comments#create",  
          as: :comments_create
  end

  namespace :admin do
    root to: "pages#index"

    namespace :blog do
      root to: "pages#index"

      resources :posts

      get "/posts(/type/:type(/tag/:tag)(/category/:category)(/page/:page))" => "posts#search",
            as: :posts_search
      
      get "/posts(/page/:page)" => "posts#index",
            as: :posts

      post "/posts/create/preview" => "posts#create_preview",
            as: :posts_create_preview

      get "/posts/preview/:id" => "posts#show_preview",
            as: :posts_preview

      delete "/posts/trash/:id" => "posts#trash",
            as: :trash_post

      resources :comments, except: :destroy

      post "/comments/update/status" => "comments#update_status",
            as: :comment_update_status

      delete "/comments/delete" => "comments#delete",
            as: :delete_comment
      
      get "/comments/page/:page" => "comments#index",
            as: :comments_page

      get "/comments/type/:type(/page/:page)" => "comments#search",
            as: :comments_search

      resources :tags

      get "tags/page/:page" => "tags#index",
            as: :tags_page
      
      delete "/tags" => "tags#destroy"

      resources :categories

      get "categories/page/:page" => "categories#index",
            as: :categories_page
      
      delete "/categories" => "categories#destroy"

      get "/links(/page/:page)" => "links#index",
            as: :links_page

      post "/links" => "links#create",
            as: :link
      
      put "/links" => "links#update",
            as: :link
      
      delete "/links" => "links#destroy"
    end

    namespace :settings do
      root to: "pages#index"
    end
  end

  

end

app/controllers/admin/blog/base_controller.rb
class Admin::Blog::BaseController < Admin::BaseController
  before_filter :create_sidebar

  #creates the sidemenu in the admin blog section
  def create_sidebar
    post_submenu = {all_posts: {url: admin_blog_posts_url,
                               title: "Edit Posts",
                               target: "",
                               submenu: nil},

                    add_post: {url: new_admin_blog_post_url,
                              title: "Add Post",
                              target: "",
                              submenu: nil},

                    categories: {url: admin_blog_categories_url,
                                title: "Edit Categories",
                                target: "",
                                submenu: nil},

                    tags: {url: admin_blog_tags_url,
                              title: "Edit Tags",
                              target: "",
                              submenu: nil} }

    # link_submenu = {all_links: {url: "#",
    #                             title: "Edit Links",
    #                             target: "",
    #                             submenu: nil},

    #                 add_link: {url: "#",
    #                           title: "Add Link",
    #                           target: "",
    #                           submenu: nil} }




    @sidebar = {posts:    {url: admin_blog_posts_url,
                          title: "Edit Posts",
                          target: "",
                          submenu: post_submenu},

                comments: {url: admin_blog_comments_url,
                          title: "Edit Comments",
                          target: "",
                          submenu: nil},

                links:    {url: admin_blog_links_page_url,
                          title: "Edit  Links",
                          target: "",
                          submenu: nil} }
  end
end

app/controllers/admin/blog/categories_controller.rb
class Admin::Blog::CategoriesController < Admin::Blog::BaseController
  before_filter :set_active
  def index
    #set categories submenu to active
    @sidebar_active << :categories
    @title = 'Categories'

    @category = Category.new

    paginate_category_page(params[:page])
  end

  def create
    @category = Category.find_or_create_by_category(params[:category])

    paginate_category_page(params[:page])#pagination module
  
  
    respond_to do |format|
      format.html
      format.js { render "admin/blog/categories/create", layout: false }
    end
  end

  def destroy
    Category.delete(params[:id])

    paginate_category_page(params[:page])

    respond_to do |format|
      format.html
      format.js { render "admin/blog/categories/update", layout: false }
    end
  end

  def update
    respond_to do |format|
      format.html 
      format.js { 
        @category = Category.find(params[:id])
        @category.update_attributes(params[:category])

        paginate_category_page(params[:page])#pagination module

        render "admin/blog/categories/update", layout: false
      }
    end
  end

  def paginate_category_page(page)
    paginate_me :categories, base_url: admin_blog_categories_url, page: page, order: 'category'
  end

  private
    #sets :posts main section to active in the side nav
    def set_active
      @sidebar_active = [:posts]
    end
end

app/controllers/admin/blog/comments_controller.rb
class Admin::Blog::CommentsController < Admin::Blog::BaseController
  before_filter :set_active

  def index
    @title = "Comments"
    @comment_types = CommentStatus.all
    @type = "all"
    
    @unapproved_id = CommentStatus.unapproved.first.id
    @approved_id = CommentStatus.approved.first.id

    paginate_me :comments, 
                base_url: admin_blog_comments_path, 
                order: 'created_at DESC', 
                where: {status_id: [@unapproved_id, @approved_id] }
  end

  def search
    @title = "Comments"
    @comment_types = CommentStatus.all
    @type = params[:type]
    current_type = @comment_types.dup.keep_if{|v| v.status == @type}.first

    paginate_me :comments, 
                base_url: admin_blog_comments_search_path(current_type.status),
                order: 'created_at DESC', 
                where: {status_id: current_type.id},
                page: params[:page] || "1"
    
    render "admin/blog/comments/index"
  end

  def update
    respond_to do |format|
      format.html
      format.js {
        
        comment = Comment.find(params[:id])
        comment.update_attributes(params[:comment])

        update_comment_page_items()
      }
    end
  end

  def update_status
    respond_to do |format|
      format.html
      format.js {
        
        set_status(params[:id],params[:status])

        update_comment_page_items()
      }
    end
  end

  def create 

    respond_to do |format|
      format.html
      format.js {
        new_comment = Comment.new(author: params[:author],
                              email: params[:email],
                              website: params[:website],
                              content: params[:content],
                              status_id: CommentStatus.approved.first.id,
                              reply_id: params[:reply_id],
                              post_id: params[:post_id],
                              ip_address: request.env['REMOTE_ADDR'])
        new_comment.save                    
        update_comment_page_items()
        
      }
    end
    
  end

  def delete
    respond_to do |format|
      format.html
      format.js {
        
        Comment.find(params[:id]).destroy

        update_comment_page_items()
      }
    end
  end

  private
    def set_active
      @sidebar_active = [:comments]
    end

    def update_comment_page_items
      @comment_types = CommentStatus.all
      @type = params[:type]
      @type = 'all' if @type == ""

      if @type == "all"
        where = {status_id: [CommentStatus.unapproved.first.id, CommentStatus.approved.first.id]} 
      else
        current_type = CommentStatus.where(status: @type).first
        where = {status_id: current_type.id}
      end
      paginate_me :comments, 
                  base_url: admin_blog_comments_path,
                  order: 'created_at DESC', 
                  where: where,
                  page: params[:page] || "1"

      render "admin/blog/comments/update.js", layout: false
    end

    def set_status(id,status)
      comment = Comment.find(id)
      comment.update_attributes(status_id: CommentStatus.send(status).first.id)
    end
end

app/controllers/admin/blog/links_controller.rb
class Admin::Blog::LinksController < Admin::Blog::BaseController
  before_filter :set_active
  def index
    @link = Link.new
    set_page_params()
  end

  def update
    Link.find(params[:link][:id]).update_attributes(params[:link])

    set_page_params()

    respond_to do |format|
      format.html
      format.js {render 'update.js', layout: false}
    end
  end

  def destroy
    Link.delete(params[:id])

    respond_to do |format|
      format.html
      format.js { render nothing: true }
    end
  end

  def create
    Link.create!(params[:link])

    set_page_params()

    respond_to do |format|
      format.html
      format.js {render 'create.js', layout: false}
    end
  end

  private
    def set_active
      @sidebar_active = [:links]
    end

    def set_page_params
      paginate_me :links, 
                  base_url: admin_blog_links_page_url,
                  order: "lower(links.name) ASC"
    end
end

app/controllers/admin/blog/pages_controller.rb
class Admin::Blog::PagesController < Admin::Blog::BaseController

  def index
    @title = "Admin"
    @post_count = Post.count
    @comment_count = Comment.count
    @spam_count = Comment.spam.count
    @approved_count = Comment.approved.count
    @pending_count = Comment.unapproved.count
    @trash_count = Comment.trash.count
    @tag_count = Tag.count
    @category_count = Category.count
  end
end

app/controllers/admin/blog/posts_controller.rb
require "modules/pagination"
require "modules/set_vars"
class Admin::Blog::PostsController < Admin::Blog::BaseController
  before_filter :set_active

  include Pagination::Posts
  include Pagination::Comments
  include SetVars::Posts

  def index
    @title = "Posts"
    #set all_posts submenu to active
    @sidebar_active << :all_posts

    @post_types = PostStatus.all
    @type = params[:type] || "all"

    paginate_index_posts(admin_blog_posts_search_url(type: @type)) # paginate module

  end

  def edit
    @title = "Edit Post"
    @post = Post.includes(:tags).find(params[:id])
    @categories = Category.order(:category)
    @tags = @post.tags().order(:tag)
    @statuses = PostStatus.all
    @current_status = @post.post_status
  end

  def search
    @title = "Posts"
    @sidebar_active << :all_posts
    # define category and tag variable for use in the view
    @category = Category.where(slug: params[:category].split(',')) unless params[:category].nil?
    @tag = Tag.where(slug: params[:tag].split(',')) unless params[:tag].nil?
    @post_types = PostStatus.all
    @type = params[:type] || "all"
    # paginate_me is used internally, which sets the @posts variable
    paginate_search_posts(@tag,@category, "/admin/blog/posts/type/#{@type}", @type)#Pagination module
  end

  def new
    @title = "New Post"
    @sidebar_active << :add_post
    @post = Post.new
    @categories = Category.order(:category)
    @statuses = PostStatus.all
    @current_status = PostStatus.published.first

    render "admin/blog/posts/edit"
  end

  def destroy
    Post.find(params[:id]).delete

    redirect_to :back
  end

  def trash
    post = Post.find(params[:id])

    post.trash!

    redirect_to :back
  end

  def update
    @preview = (params[:commit] == "Preview")
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])

    set_params()
    get_categories_tags()
    attempt_to_save_post()
  end

  def create
    params[:post][:user_id] = current_user.id
    @post = Post.new(params[:post])

    set_params()
    get_categories_tags()

    attempt_to_save_post()
  end

  # seems a bit crude, I'll need to clean this up at some point
  # I need to go back and remove the unique validation for titles on posts so I can add
  # an additional save status, then I don't need to add the preview keyword into the current
  # title and the preview should work on page refresh instead of being a one time use
  def create_preview
    params[:post][:user_id] = current_user.id
    params[:post][:title] << " %preview%"

    #destroy the preview if one exists (result of hitting preview multiple times before post submit)
    preview = Post.where(title: params[:post][:title]).first()
    if preview
      preview.destroy
    end

    @post = Post.new(params[:post])

    set_params()
    get_categories_tags()
    @post.status_id = PostStatus.draft.first.id

    @post.categories = Category.where(category: params[:categories])
    @post.tags = Tag.where(tag: params[:tags])
    if @post.save
      respond_to do |format|
        format.html
        format.js { render json: @post.id }
      end
    else
      @errors = @post.errors.messages
      respond_to do |format|
        format.html
        format.js { render json: @errors }
      end
    end
  end

  def show_preview
    @title = "Preview"

    @comment = Comment.new

    # sort of hacky, when the preview is loaded the temporary saved draft in the DB is deleted
    # so if the user refreshes the preview it redirects to the home page, the preview expires
    # after one use. I don't really like this, the post model needs to be tweaked to allow for
    # saved or preview/draft post status with a copy of a post with the same title can be saved.

    begin
    temp_post = Post.find(params[:id]) 
    @post = temp_post
    @post.title = @post.title.split("%preview%")[0]
    @categories = Category.all
    @tags = Tag.all
    @captcha = Captcha.new

    # paginate_me is used internally, which sets the @comments variable
    paginate_comments_for_post(@post) #Pagination module    
    @comment_tree = {}
    temp_post.delete
    
    render "blog/posts/show", layout: "blog/layouts/application"
    rescue
      redirect_to blog_root_url
    end
  end

  private
    def set_active
      @sidebar_active = [:posts]
    end

    def set_params
      @post.categories = params[:categories].map {|c| Category.find_or_create_by_category(category: c)} unless params[:categories].nil?
      @post.tags = params[:tags].map {|t| Tag.find_or_create_by_tag(tag: t)} unless params[:tags].nil?
      @post.status_id = params[:status]
    end

    def get_categories_tags
      @categories = Category.order(:category)
      @tags = @post.tags().order(:tag)
    end

    def attempt_to_save_post
      if @post.save
        flash[:success] = "Post was updated successfully"
        redirect_to :back
      else
        flash[:form_error] = "uh oh! There was a problem"
        @errors = @post.errors.messages
        render "admin/blog/posts/edit"
      end
    end
end

app/controllers/admin/blog/tags_controller.rb
class Admin::Blog::TagsController < Admin::Blog::BaseController
  before_filter :set_active
  def index
    #set tag submenu to active
    @sidebar_active << :tags
    @title = 'Tags'
    
    respond_to do |format|
      format.html {
        @tag = Tag.new
        paginate_tag_page(params[:page])
      }
      format.json {render json:  Tag.select('tag').map{|t| t.tag} }
    end
    
  end

  def create
    respond_to do |format|
      format.html
      format.js { 
        @tags = []

        if params[:tags]
          tags = params[:tags].split(',')
          tags.each do |t|
            @tags.push(Tag.find_or_create_by_tag(tag: t))
          end
        end

        if params[:tag]
          Tag.find_or_create_by_tag(tag: params[:tag][:tag])
          paginate_tag_page(params[:page])
        end

        render "admin/blog/tags/create", layout: false 
      }
    end
  end

  def destroy
    respond_to do |format|
      format.html
      format.js { 
        @tag = params[:tag]

        #Tag.delete(Tag.where(slug: params[:tag]).first.id)
        Tag.delete(params[:tag_id])

        paginate_tag_page(params[:page])

        render "admin/blog/tags/update", layout: false 
      }
    end
  end

  def update
    respond_to do |format|
      format.html
      format.js {
        @tag = Tag.find(params[:id])
        @tag.update_attributes(params[:tag])

        paginate_tag_page(params[:page])
        render "admin/blog/tags/update", layout: false
      }
    end   
  end

  private
    def paginate_tag_page(page)
      paginate_me :tags, base_url: admin_blog_tags_url, page: page, order: 'tag'
    end

    def set_active
      @sidebar_active = [:posts]
    end
end

app/controllers/blog/base_controller.rb
class Blog::BaseController < ApplicationController
  layout "blog/layouts/application"
  before_filter :load_cats_tags

  def load_cats_tags
    @categories = Category.all
    @tags = Tag.all
  end

end

app/helpers/blog_helper.rb
module BlogHelper
   
end

app/views/blog/posts/_comment_form.haml
= content_tag(:h3,"Reply to the comment by #{@reply_comment.author}", id: 'reply') unless @reply_comment.nil?
= form_for @comment, url: blog_comments_create_path do |f|
  %p
    = render "shared/form_error", errors: @errors, type: :author
    = f.label :author, "Author Name (Required)"
    %br
    = f.text_field :author
  %p 
    = render "shared/form_error", errors: @errors, type: :email
    = f.label :email, "Email address (Required, but won't be displayed)"
    %br
    = f.text_field :email
  %p 
    = f.label :website, "Website (Optional)"
    %br
    = f.text_field :website
  %p 
    = render "shared/form_error", errors: @errors, type: :content
    = f.label :content, "Comment (supports Markdown) "
    = render "blog/posts/markdown_cheat_sheet"
    %br
    = f.text_area :content
    = f.hidden_field :post_id, value: @post.id
    = f.hidden_field :slug, value: @post.slug
    = f.hidden_field :reply_id, value: @reply_comment.id unless @reply_comment.nil?
    = hidden_field_tag :captcha_image,@captcha.image
    %p= image_tag(@captcha.image_path, alt: 'captcha image', title: 'captcha image')
    %p Human test! Name the animal.
    = @captcha.form_fields
      
  %p 
    = f.submit "Post Comment"

app/views/blog/posts/_comments.haml
%ul{class: 'comment_list'} 
  - comment_tree.each do |comment_id,c|
    - comment = c[:comment]
    - if comment.reply_id.nil? || reply
      %li{class: klass}
        %h3= "By #{comment.author}"
        %p{class: 'date'}= "on #{comment.updated_at.strftime("%A %b %d, %Y")}"
        %p= link_to "#{comment.author}'s Website", comment.website, 
                    title: "#{comment.author}'s Website", 
                    class: 'website' unless comment.website == ""
        %p= preserve(markdown(comment.content))

        = link_to "Reply", "#{blog_post_url(slug: comment.post.slug, reply_id: comment_id)}#reply"
      %li{class: "reply_container"}  
        = render("blog/posts/comments", klass: "reply", 
          comment_tree: c[:replies], reply: true) if c[:replies].length > 0
     
    

app/views/blog/posts/_markdown_cheat_sheet.haml
%a{href: '#', class: "markdown_help"} Markdown Help
.markdown_cheat_sheet
  %dl
    %dt
      Paragraphs and Linebreaks
    %dd
      %div
        Markdown understands normal linebreaks, use return and seperate your paragraphs as you normally would.
    %dt
      Headings
    %dd 
      %div
        There are multiple levels of headings for markdown starting at a heading 1 and moving up to 6. Heading 1 is the largest sized header, so increasing the header number will progressively get smaller. A heading is preceeded by the '#' symbol. The value of the heading is represented by how many '#' are used. For example the largest heading, a heading 1 would be writting as follows:
        %pre #Heading 1
        %h1 Heading 1
        %pre ##Heading 2
        %h2 Heading 2
        %pre ###Heading 3
        %h3 Heading 3
    %dt 
      Lists
    %dd
      %div
        Lists can be created in 2 different ways. Bulleted lists simply need an asterisk followed by a single space, for example:
        -# haml was messing up the line breaks using normal syntax
        %pre= "* item 1\n* item 2\n* item 3"
        
        results in:
        %ul
          %li item 1
          %li item 2
          %li item 3 
        
        Numbered lists are created by putting numbers followed by a period and a space instead of an asterisk, for example:

        %pre= "1. item 1\n2. item 2\n3. item 3"

        results in:

        %ol
          %li item 1
          %li item 2
          %li item 3
    %dt 
      Links
    %dd
      %div
        Links are created by putting square brackets around your link text and adding the url in parentheses after the brackets, followed by an option title(The title is the rollover text), for example:

        %pre [My Website](http://somewebsite.com/ "Title of my site")
        results in:
        %a{href: 'http://somewebsite.com/', title: 'Title of my site'} My Website
        %br
        %br
        This version has the title removed
        %pre [My Website](http://somewebsite.com/)

        results in:

        %a{href: 'http://somewebsite.com/'} My Website
    %dt
      Emphasis
    %dd
      %div
        Emphasis can be added to words in as either bold or italic text. Wrapping a word or words with
        %code * *
        will result in italic text, similarly wrapping a word or words with
        %code ** **
        will result in bold text, for example:

        %pre **look at me!**

        results in:
        %br
        %strong look at me!

        %pre *I'm sort of important*

        results in:
        %br
        %em I'm sort of important
    %dt
      Images
    %dd
      %div
        Images can be added almost the same as links are created. The format looks the same with the exception that an exclamation point precedes the initial brackets. For example:

        %pre= "![short description of image, it's a puppy!](#{asset_path('puppy.png')} 'puppy image title')"
        results in:
        %br
        =image_tag 'puppy.png', title: 'puppy image title', alt: 'short description of image, it\'s a puppy!'
    %dt
      Horizontal Rules
    %dd
      %div
        Horizontal rules can be created by using 3 or more
        %code --- 
        this is useful for creating breaks in content. For example:
        %pre ---
        results in:

        %hr
    %dt
      Blockquotes
    %dd
      %div
        Block quotes are similar to quotes in email. You can either place a 
        %code >
        after each line or precede the first character in a paragraph with a single
        %code >
        , for example:

        %pre >"This is a quote from someone who is very important."

        results in:

        %blockquote "This is a quote from someone who is very important."
      
    
  %a{class: 'close', href: '#'} close
      

app/views/blog/posts/_post.haml
- no_link ||= false

%h2= (!no_link ? link_to(post.title, blog_post_url(slug: post.slug)) : post.title)
%p= post.user.user_name
%p= "Posted on #{post.updated_at.strftime("%A %b %d, %Y")}"
%p= preserve(markdown(post.content))
%strong
  tags
  = "(#{post.tags_count})"
%ul 
  - post.tags.each do |t|
    %li= t.tag
%strong 
  categories
  = "(#{post.categories_count})"
%ul
  - post.categories.each do |c|
    %li= c.category

app/views/blog/posts/index.haml
%ul{class: "posts"}
  - @posts.each do |p|
    %li= render "blog/posts/post", post: p

= paginate_for :posts do |p|
  %span{class: "right"}
    = p.link_to_last
    = p.link_to_next
  = p.page_out_of_total
  %span{class: "left"}
    = p.link_to_previous
    =  p.link_to_first 

app/views/blog/posts/search.haml
%h3 
  Posts
  - unless @category.nil?
    = " in #{(@category.length > 1 ? 'categories' : 'category')} - "
    - @category.each do |c|
      = "#{c.category}"

  - unless @tag.nil?
    = " tagged with - "
    - @tag.each do |t|
      = "#{t.tag}"

%ul{class: "posts"}
  - @posts.each do |p|
    %li= render "blog/posts/post", post: p

= paginate_for :posts do |p|
  %span{class: "right"}
    = p.link_to_last
    = p.link_to_next
  = p.page_out_of_total
  %span{class: "left"}
    = p.link_to_previous
    = p.link_to_first 

app/views/blog/posts/show.haml
.post

  = render "blog/posts/post", post: @post, no_link: true

  = render "blog/posts/comment_form"

  = render "blog/posts/comments", comment_tree: @comment_tree, klass: "comment"
  
  = paginate_for :comments do |p|
    %span{class: "right"}
      = p.link_to_last
      = p.link_to_next
    = p.page_out_of_total
    %span{class: "left"}
      = p.link_to_previous
      =  p.link_to_first 
    