config/routes.rb
BlogBase::Application.routes.draw do
  devise_for :users, 
             path_names: {sign_up: "register"} # defaults the sign_up path to use register instead

  root to: "pages#home", 
       via: :get

  namespace :blog do

    root to: "posts#index", via: :get

    get "/page/:page" => "posts#index", 
          as: :page

    get "/posts(/tag/:tag)(/category/:category)(/page/:page)" => "posts#search", 
          as: :posts_search, 
          defaults: {page: 1}

    get "/feed" => "posts#feed",
          as: :feed,
          defaults: {format: 'atom'}

    get "/rss" => redirect("/blog/feed")

    get "/atom" => redirect("/blog/feed")

    get "/:slug(/comment(/reply/:reply_id)(:comment_id))(/page/:page)" => "posts#show", 
          as: :post

    post "/comments/create" => "comments#create",  
          as: :comments_create
  end

  namespace :admin do
    root to: "pages#index"

    namespace :blog do
      root to: "pages#index"

      resources :posts

      get "/posts(/type/:type(/tag/:tag)(/category/:category)(/page/:page))" => "posts#search",
            as: :posts_search
      
      get "/posts(/page/:page)" => "posts#index",
            as: :posts

      post "/posts/create/preview" => "posts#create_preview",
            as: :posts_create_preview

      get "/posts/preview/:id" => "posts#show_preview",
            as: :posts_preview

      delete "/posts/trash/:id" => "posts#trash",
            as: :trash_post

      resources :comments, except: :destroy

      post "/comments/update/status" => "comments#update_status",
            as: :comment_update_status

      delete "/comments/delete" => "comments#delete",
            as: :delete_comment
      
      get "/comments/page/:page" => "comments#index",
            as: :comments_page

      get "/comments/type/:type(/page/:page)" => "comments#search",
            as: :comments_search

      resources :tags

      get "tags/page/:page" => "tags#index",
            as: :tags_page
      
      delete "/tags" => "tags#destroy"

      resources :categories

      get "categories/page/:page" => "categories#index",
            as: :categories_page
      
      delete "/categories" => "categories#destroy"

      get "/links(/page/:page)" => "links#index",
            as: :links_page

      post "/links" => "links#create",
            as: :link
      
      put "/links" => "links#update",
            as: :link
      
      delete "/links" => "links#destroy"
    end

    namespace :settings do
      root to: "pages#index"
    end
  end

  

end

app/controllers/admin/blog/base_controller.rb
class Admin::Blog::BaseController < Admin::BaseController
  before_filter :create_sidebar

  #creates the sidemenu in the admin blog section
  def create_sidebar
    post_submenu = {all_posts: {url: admin_blog_posts_url,
                               title: "Edit Posts",
                               target: "",
                               submenu: nil},

                    add_post: {url: new_admin_blog_post_url,
                              title: "Add Post",
                              target: "",
                              submenu: nil},

                    categories: {url: admin_blog_categories_url,
                                title: "Edit Categories",
                                target: "",
                                submenu: nil},

                    tags: {url: admin_blog_tags_url,
                              title: "Edit Tags",
                              target: "",
                              submenu: nil} }

    # link_submenu = {all_links: {url: "#",
    #                             title: "Edit Links",
    #                             target: "",
    #                             submenu: nil},

    #                 add_link: {url: "#",
    #                           title: "Add Link",
    #                           target: "",
    #                           submenu: nil} }




    @sidebar = {posts:    {url: admin_blog_posts_url,
                          title: "Edit Posts",
                          target: "",
                          submenu: post_submenu},

                comments: {url: admin_blog_comments_url,
                          title: "Edit Comments",
                          target: "",
                          submenu: nil},

                links:    {url: admin_blog_links_page_url,
                          title: "Edit  Links",
                          target: "",
                          submenu: nil} }
  end
end

app/controllers/admin/blog/categories_controller.rb
class Admin::Blog::CategoriesController < Admin::Blog::BaseController
  before_filter :set_active
  def index
    #set categories submenu to active
    @sidebar_active << :categories
    @title = 'Categories'

    @category = Category.new

    paginate_category_page(params[:page])
  end

  def create
    @category = Category.find_or_create_by_category(params[:category])

    paginate_category_page(params[:page])#pagination module
  
  
    respond_to do |format|
      format.html
      format.js { render "admin/blog/categories/create", layout: false }
    end
  end

  def destroy
    Category.delete(params[:id])

    paginate_category_page(params[:page])

    respond_to do |format|
      format.html
      format.js { render "admin/blog/categories/update", layout: false }
    end
  end

  def update
    respond_to do |format|
      format.html 
      format.js { 
        @category = Category.find(params[:id])
        @category.update_attributes(params[:category])

        paginate_category_page(params[:page])#pagination module

        render "admin/blog/categories/update", layout: false
      }
    end
  end

  def paginate_category_page(page)
    paginate_me :categories, base_url: admin_blog_categories_url, page: page, order: 'category'
  end

  private
    #sets :posts main section to active in the side nav
    def set_active
      @sidebar_active = [:posts]
    end
end

app/controllers/admin/blog/comments_controller.rb
class Admin::Blog::CommentsController < Admin::Blog::BaseController
  before_filter :set_active

  def index
    @title = "Comments"
    @comment_types = CommentStatus.all
    @type = "all"
    
    @unapproved_id = CommentStatus.unapproved.first.id
    @approved_id = CommentStatus.approved.first.id

    paginate_me :comments, 
                base_url: admin_blog_comments_path, 
                order: 'created_at DESC', 
                where: {status_id: [@unapproved_id, @approved_id] }
  end

  def search
    @title = "Comments"
    @comment_types = CommentStatus.all
    @type = params[:type]
    current_type = @comment_types.dup.keep_if{|v| v.status == @type}.first

    paginate_me :comments, 
                base_url: admin_blog_comments_search_path(current_type.status),
                order: 'created_at DESC', 
                where: {status_id: current_type.id},
                page: params[:page] || "1"
    
    render "admin/blog/comments/index"
  end

  def update
    respond_to do |format|
      format.html
      format.js {
        
        comment = Comment.find(params[:id])
        comment.update_attributes(params[:comment])

        update_comment_page_items()
      }
    end
  end

  def update_status
    respond_to do |format|
      format.html
      format.js {
        
        set_status(params[:id],params[:status])

        update_comment_page_items()
      }
    end
  end

  def create 

    respond_to do |format|
      format.html
      format.js {
        new_comment = Comment.new(author: params[:author],
                              email: params[:email],
                              website: params[:website],
                              content: params[:content],
                              status_id: CommentStatus.approved.first.id,
                              reply_id: params[:reply_id],
                              post_id: params[:post_id],
                              ip_address: request.env['REMOTE_ADDR'])
        new_comment.save                    
        update_comment_page_items()
        
      }
    end
    
  end

  def delete
    respond_to do |format|
      format.html
      format.js {
        
        Comment.find(params[:id]).destroy

        update_comment_page_items()
      }
    end
  end

  private
    def set_active
      @sidebar_active = [:comments]
    end

    def update_comment_page_items
      @comment_types = CommentStatus.all
      @type = params[:type]
      @type = 'all' if @type == ""

      if @type == "all"
        where = {status_id: [CommentStatus.unapproved.first.id, CommentStatus.approved.first.id]} 
      else
        current_type = CommentStatus.where(status: @type).first
        where = {status_id: current_type.id}
      end
      paginate_me :comments, 
                  base_url: admin_blog_comments_path,
                  order: 'created_at DESC', 
                  where: where,
                  page: params[:page] || "1"

      render "admin/blog/comments/update.js", layout: false
    end

    def set_status(id,status)
      comment = Comment.find(id)
      comment.update_attributes(status_id: CommentStatus.send(status).first.id)
    end
end

app/controllers/admin/blog/links_controller.rb
class Admin::Blog::LinksController < Admin::Blog::BaseController
  before_filter :set_active
  def index
    @link = Link.new
    set_page_params()
  end

  def update
    Link.find(params[:link][:id]).update_attributes(params[:link])

    set_page_params()

    respond_to do |format|
      format.html
      format.js {render 'update.js', layout: false}
    end
  end

  def destroy
    Link.delete(params[:id])

    respond_to do |format|
      format.html
      format.js { render nothing: true }
    end
  end

  def create
    Link.create!(params[:link])

    set_page_params()

    respond_to do |format|
      format.html
      format.js {render 'create.js', layout: false}
    end
  end

  private
    def set_active
      @sidebar_active = [:links]
    end

    def set_page_params
      paginate_me :links, 
                  base_url: admin_blog_links_page_url,
                  order: "lower(links.name) ASC"
    end
end

app/controllers/admin/blog/pages_controller.rb
class Admin::Blog::PagesController < Admin::Blog::BaseController

  def index
    @title = "Admin"
    @post_count = Post.count
    @comment_count = Comment.count
    @spam_count = Comment.spam.count
    @approved_count = Comment.approved.count
    @pending_count = Comment.unapproved.count
    @trash_count = Comment.trash.count
    @tag_count = Tag.count
    @category_count = Category.count
  end
end

app/controllers/admin/blog/posts_controller.rb
require "modules/pagination"
require "modules/set_vars"
class Admin::Blog::PostsController < Admin::Blog::BaseController
  before_filter :set_active

  include Pagination::Posts
  include Pagination::Comments
  include SetVars::Posts

  def index
    @title = "Posts"
    #set all_posts submenu to active
    @sidebar_active << :all_posts

    @post_types = PostStatus.all
    @type = params[:type] || "all"

    paginate_index_posts(admin_blog_posts_search_url(type: @type)) # paginate module

  end

  def edit
    @title = "Edit Post"
    @post = Post.includes(:tags).find(params[:id])
    @categories = Category.order(:category)
    @tags = @post.tags().order(:tag)
    @statuses = PostStatus.all
    @current_status = @post.post_status
  end

  def search
    @title = "Posts"
    @sidebar_active << :all_posts
    # define category and tag variable for use in the view
    @category = Category.where(slug: params[:category].split(',')) unless params[:category].nil?
    @tag = Tag.where(slug: params[:tag].split(',')) unless params[:tag].nil?
    @post_types = PostStatus.all
    @type = params[:type] || "all"
    # paginate_me is used internally, which sets the @posts variable
    paginate_search_posts(@tag,@category, "/admin/blog/posts/type/#{@type}", @type)#Pagination module
  end

  def new
    @title = "New Post"
    @sidebar_active << :add_post
    @post = Post.new
    @categories = Category.order(:category)
    @statuses = PostStatus.all
    @current_status = PostStatus.published.first

    render "admin/blog/posts/edit"
  end

  def destroy
    Post.find(params[:id]).delete

    redirect_to :back
  end

  def trash
    post = Post.find(params[:id])

    post.trash!

    redirect_to :back
  end

  def update
    @preview = (params[:commit] == "Preview")
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])

    set_params()
    get_categories_tags()
    attempt_to_save_post()
  end

  def create
    params[:post][:user_id] = current_user.id
    @post = Post.new(params[:post])

    set_params()
    get_categories_tags()

    attempt_to_save_post()
  end

  # seems a bit crude, I'll need to clean this up at some point
  # I need to go back and remove the unique validation for titles on posts so I can add
  # an additional save status, then I don't need to add the preview keyword into the current
  # title and the preview should work on page refresh instead of being a one time use
  def create_preview
    params[:post][:user_id] = current_user.id
    params[:post][:title] << " %preview%"

    #destroy the preview if one exists (result of hitting preview multiple times before post submit)
    preview = Post.where(title: params[:post][:title]).first()
    if preview
      preview.destroy
    end

    @post = Post.new(params[:post])

    set_params()
    get_categories_tags()
    @post.status_id = PostStatus.draft.first.id

    @post.categories = Category.where(category: params[:categories])
    @post.tags = Tag.where(tag: params[:tags])
    if @post.save
      respond_to do |format|
        format.html
        format.js { render json: @post.id }
      end
    else
      @errors = @post.errors.messages
      respond_to do |format|
        format.html
        format.js { render json: @errors }
      end
    end
  end

  def show_preview
    @title = "Preview"

    @comment = Comment.new

    # sort of hacky, when the preview is loaded the temporary saved draft in the DB is deleted
    # so if the user refreshes the preview it redirects to the home page, the preview expires
    # after one use. I don't really like this, the post model needs to be tweaked to allow for
    # saved or preview/draft post status with a copy of a post with the same title can be saved.

    begin
    temp_post = Post.find(params[:id]) 
    @post = temp_post
    @post.title = @post.title.split("%preview%")[0]
    @categories = Category.all
    @tags = Tag.all
    @captcha = Captcha.new

    # paginate_me is used internally, which sets the @comments variable
    paginate_comments_for_post(@post) #Pagination module    
    @comment_tree = {}
    temp_post.delete
    
    render "blog/posts/show", layout: "blog/layouts/application"
    rescue
      redirect_to blog_root_url
    end
  end

  private
    def set_active
      @sidebar_active = [:posts]
    end

    def set_params
      @post.categories = params[:categories].map {|c| Category.find_or_create_by_category(category: c)} unless params[:categories].nil?
      @post.tags = params[:tags].map {|t| Tag.find_or_create_by_tag(tag: t)} unless params[:tags].nil?
      @post.status_id = params[:status]
    end

    def get_categories_tags
      @categories = Category.order(:category)
      @tags = @post.tags().order(:tag)
    end

    def attempt_to_save_post
      if @post.save
        flash[:success] = "Post was updated successfully"
        redirect_to :back
      else
        flash[:form_error] = "uh oh! There was a problem"
        @errors = @post.errors.messages
        render "admin/blog/posts/edit"
      end
    end
end

app/controllers/admin/blog/tags_controller.rb
class Admin::Blog::TagsController < Admin::Blog::BaseController
  before_filter :set_active
  def index
    #set tag submenu to active
    @sidebar_active << :tags
    @title = 'Tags'
    
    respond_to do |format|
      format.html {
        @tag = Tag.new
        paginate_tag_page(params[:page])
      }
      format.json {render json:  Tag.select('tag').map{|t| t.tag} }
    end
    
  end

  def create
    respond_to do |format|
      format.html
      format.js { 
        @tags = []

        if params[:tags]
          tags = params[:tags].split(',')
          tags.each do |t|
            @tags.push(Tag.find_or_create_by_tag(tag: t))
          end
        end

        if params[:tag]
          Tag.find_or_create_by_tag(tag: params[:tag][:tag])
          paginate_tag_page(params[:page])
        end

        render "admin/blog/tags/create", layout: false 
      }
    end
  end

  def destroy
    respond_to do |format|
      format.html
      format.js { 
        @tag = params[:tag]

        #Tag.delete(Tag.where(slug: params[:tag]).first.id)
        Tag.delete(params[:tag_id])

        paginate_tag_page(params[:page])

        render "admin/blog/tags/update", layout: false 
      }
    end
  end

  def update
    respond_to do |format|
      format.html
      format.js {
        @tag = Tag.find(params[:id])
        @tag.update_attributes(params[:tag])

        paginate_tag_page(params[:page])
        render "admin/blog/tags/update", layout: false
      }
    end   
  end

  private
    def paginate_tag_page(page)
      paginate_me :tags, base_url: admin_blog_tags_url, page: page, order: 'tag'
    end

    def set_active
      @sidebar_active = [:posts]
    end
end

app/controllers/blog/base_controller.rb
class Blog::BaseController < ApplicationController
  layout "blog/layouts/application"
  before_filter :load_cats_tags

  def load_cats_tags
    @categories = Category.all
    @tags = Tag.all
  end

end

app/helpers/blog_helper.rb
module BlogHelper
   
end

app/views/admin/blog/posts/_category_list.haml
- checked = post.categories.to_a
- categories.each do |c|
  %li
    = check_box_tag('categories[]', c.id, checked.include?(c), id: "category#{c.id}") 
    = content_tag(:label, c.category, for: "category#{c.id}")

app/views/admin/blog/posts/_posts_table.haml
- type ||= "all"
%table{class: "info_table"}
  %thead
    %tr
      %th{title: "Post Title"} Title
      %th{title: "Post Author"} Author
      %th{title: "Post Tags"} Tags
      %th{title: "Post Categories"} Categories
      %th{title: "Total Comments"} C
      %th{title: "Last Updated"} Last Updated
  %tbody
    - count = 0
    - posts.each do |p|
      - count += 1
      %tr{class: (count % 2 == 0 ? "row_stripe": nil)}
        %td{title: "Post Title"}= p.title
        %td{title: "Post Author"}= (p.user.name.length > 0 ? p.user.name : p.user.user_name)
        %td{title: "Post Tags"}
          = p.tags.map{|t| link_to(t.tag, admin_blog_posts_search_url(type: type, tag: t.slug,page: 1))}.join(", ").html_safe

        %td{title: "Post Categories"} 
          = p.categories.map{|c| link_to(c.category, admin_blog_posts_search_url(type: type,category: c.slug,page: 1))}.join(", ").html_safe

        %td{title: "Total Comments"}= (p.comments_count.nil? ? "0" : p.comments_count)
        %td{title: "Last Updated"}= p.updated_at.strftime("%A %b %d, %Y")
          
      %tr{class: "#{(count % 2 == 0 ? "row_stripe": nil)}"}
        %td{colspan: 5}
          %div{class: "roll_over"}
            = link_to 'edit', edit_admin_blog_post_url(p.id)
            = " | "
            - if type == "trashed"  
              = button_to 'delete', { controller: 'admin/blog/posts',action: :destroy,id: p.id}, method: :delete, confirm: "Are you sure you want to permanent delete this post? (this action is not reversible)"
            - else
              = button_to 'trash', { controller: 'admin/blog/posts',action: :trash,id: p.id}, method: :delete, confirm: "Are you sure you want to trash this post?"
            = " | " 
            = link_to("view", blog_post_url(p.slug))
        - post_status = @post_types.select{|ps| ps.id == p.status_id }.first
        %td{title: "Post Status"}= post_status.status unless post_status.nil?
  
      

app/views/admin/blog/posts/edit.haml
%script
  window.name = 'myWindow'

= render "admin/blog/posts/markdown_cheat_sheet"
= form_for [:admin, :blog, @post] do |f|
  .form_col1
    %p 
      = render "shared/form_error", errors: @errors, type: :title
      = f.label :title
      %br
      = f.text_field :title
    %p
      = render "shared/form_error", errors: @errors, type: :content 
      = f.label :content
      %br
      = f.text_area :content
      = f.hidden_field :id
    %p 
      = f.submit
      = link_to 'Preview', '#', class: 'post_preview button'
  .form_col2
    %p
      = label_tag 'status', 'Post Status'
      = select_tag 'status', options_from_collection_for_select(@statuses, "id", "status", @current_status.id)
    -#category list
    = f.label :categories
    %ul{class: "category_list"}
      = render "admin/blog/categories/category_list", post: @post, categories: @categories
    %p
      %input{class: "new_category"}
      %br
      = link_to('New Category', '#', class: 'new_category_button button' )
        
    -# tag list
    %ul{class: "tag_list"}
      = render "admin/blog/tags/tag_list", post: @post, tags: @tags
    
    %input{class: "tag_input"}

app/views/admin/blog/posts/index.haml
%h1 Posts
%ul{class: "admin_list_types"}
  %li= "#{link_to("All", admin_blog_posts_url, class: (@type == 'all' ? 'active' : nil))} | ".html_safe
  - types = @post_types.map do |t|
    - content_tag(:li, link_to(t.status.capitalize, admin_blog_posts_search_url(type: t.status)))
  = types.join(content_tag(:li, " | ")).html_safe
  

= render "admin/blog/posts/posts_table", posts: @posts, type: @type

= paginate_for :posts do |p|
  %span{class: "right"}
    = p.link_to_last
    = p.link_to_next
  = p.page_out_of_total
  %span{class: "left"}
    = p.link_to_previous
    = p.link_to_first                                                

app/views/admin/blog/posts/new.haml
%h1 new post

app/views/admin/blog/posts/search.haml
%h1
  Posts
  - unless @category.nil?
    = " in #{(@category.length > 1 ? 'categories' : 'category')} - "
    - @category.each do |c|
      = "#{c.category}"

  - unless @tag.nil?
    = " tagged with - "
    - @tag.each do |t|
      = "#{t.tag}"

=# post type nav
%ul{class: "admin_list_types"}
  %li= "#{link_to("All", admin_blog_posts_url)} | ".html_safe
  - types = @post_types.map do |t| 
    - content_tag(:li, link_to(t.status.capitalize, admin_blog_posts_search_path(type: t.status),class: (@type == t.status ? 'active' : nil)))
  = types.join(content_tag(:li, " | ")).html_safe

= render "admin/blog/posts/posts_table", posts: @posts, type: @type

= paginate_for :posts do |p|
  %span{class: "right"}
    = p.link_to_last
    = p.link_to_next
  = p.page_out_of_total
  %span{class: "left"}
    = p.link_to_previous
    = p.link_to_first                                                

app/views/admin/blog/posts/show.haml
= form_for @post, url: edit_admin_blog_post_url(@post.id) do |f|
  %p 
    = f.label :title
    %br
    = f.text_field :title
  %p 
    = f.label :content
    %br
    = f.text_area :content