config/routes.rb
BlogBase::Application.routes.draw do
  devise_for :users, 
             path_names: {sign_up: "register"} # defaults the sign_up path to use register instead

  root to: "pages#home", 
       via: :get

  namespace :blog do

    root to: "posts#index", via: :get

    get "/page/:page" => "posts#index", 
          as: :page

    get "/posts(/tag/:tag)(/category/:category)(/page/:page)" => "posts#search", 
          as: :posts_search, 
          defaults: {page: 1}

    get "/feed" => "posts#feed",
          as: :feed,
          defaults: {format: 'atom'}

    get "/rss" => redirect("/blog/feed")

    get "/atom" => redirect("/blog/feed")

    get "/:slug(/comment(/reply/:reply_id)(:comment_id))(/page/:page)" => "posts#show", 
          as: :post

    post "/comments/create" => "comments#create",  
          as: :comments_create
  end

  namespace :admin do
    root to: "pages#index"

    namespace :blog do
      root to: "pages#index"

      resources :posts

      get "/posts(/type/:type(/tag/:tag)(/category/:category)(/page/:page))" => "posts#search",
            as: :posts_search
      
      get "/posts(/page/:page)" => "posts#index",
            as: :posts

      post "/posts/create/preview" => "posts#create_preview",
            as: :posts_create_preview

      get "/posts/preview/:id" => "posts#show_preview",
            as: :posts_preview

      delete "/posts/trash/:id" => "posts#trash",
            as: :trash_post

      resources :comments, except: :destroy

      post "/comments/update/status" => "comments#update_status",
            as: :comment_update_status

      delete "/comments/delete" => "comments#delete",
            as: :delete_comment
      
      get "/comments/page/:page" => "comments#index",
            as: :comments_page

      get "/comments/type/:type(/page/:page)" => "comments#search",
            as: :comments_search

      resources :tags

      get "tags/page/:page" => "tags#index",
            as: :tags_page
      
      delete "/tags" => "tags#destroy"

      resources :categories

      get "categories/page/:page" => "categories#index",
            as: :categories_page
      
      delete "/categories" => "categories#destroy"

      get "/links(/page/:page)" => "links#index",
            as: :links_page

      post "/links" => "links#create",
            as: :link
      
      put "/links" => "links#update",
            as: :link
      
      delete "/links" => "links#destroy"
    end

    namespace :settings do
      root to: "pages#index"
    end
  end

  

end

app/views/admin/layouts/_footer.haml
#footer
  %ul 
    %li copyright blog, 2011
    %li= link_to "Privacy Policy", "#"
    %li= link_to "Contact", "#"
    %li= link_to "Terms", "#"

app/views/admin/layouts/_head.haml
%head
  %title= admin_title
  = csrf_meta_tag

  = render "admin/layouts/stylesheets"

app/views/admin/layouts/_header.haml
%nav{class: "main_menu"}
  = nav_sign_in_items(true)
    
  %ul
    %li= link_to "Admin Home",admin_root_url
    %li= link_to "Blog",admin_blog_root_url
    %li= link_to "Settings",admin_settings_root_url

app/views/admin/layouts/_main_nav.haml
%h2 Categories
%ul 
  - @categories.each do |c|
    %li
      = link_to c.category, blog_category_search_url(c.id)
      = "(#{c.posts_count})"

%h2 Tags
%ul
  - @tags.each do |t|
    %li
      = link_to t.tag, blog_tag_search_url(t.id)
      = "(#{t.posts_count})"

app/views/admin/layouts/_nav.haml
%h2 Categories
%ul 
  - @categories.each do |c|
    %li
      = link_to c.category, blog_category_search_url(c.id)
      = "(#{c.posts_count})"

%h2 Tags
%ul
  - @tags.each do |t|
    %li
      = link_to t.tag, blog_tag_search_url(t.id)
      = "(#{t.posts_count})"

app/views/admin/layouts/_page_nav.haml
%h2 Categories
%ul 
  - @categories.each do |c|
    %li
      = link_to c.category, blog_category_search_url(c.id)
      = "(#{c.posts_count})"

%h2 Tags
%ul
  - @tags.each do |t|
    %li
      = link_to t.tag, blog_tag_search_url(t.id)
      = "(#{t.posts_count})"

app/views/admin/layouts/_sidebar.haml
-# nested_items = sidebar_items = {name: {url: "http://www.yoursite.com", 
-#                                        title: "click here to go to yoursite"
-#                                        target: "",
-#                                        submenu: nested_items}}

-# active accepts an array of sidemenu symbols. So if your on the ':all_posts' submenu page within ':posts'
-# active would need an array with both active = [:posts, :all_posts] for correct links to be set active

- sidebar_items ||= {}
- active ||= []
- submenu ||= nil
%ul{class: (submenu ? nil : "sidebar")}
  - sidebar_items.each do |k,v|
    %li{class: (!v[:submenu].nil? && v[:submenu].length > 1 ? "has_submenu" : nil)}
      = link_to k.to_s.gsub("_", " ").titleize, v[:url], class: (!active.nil? && active.include?(k) ? "active" : "")
      - unless v[:submenu].nil?
        %li{class: "submenu"}
          = render "admin/layouts/sidebar", sidebar_items: v[:submenu],active: active, submenu: true
  

app/views/admin/layouts/_stylesheets.haml
/[if lt IE 9]
  %script{src: "http://html5shiv.googlecode.com/svn/trunk/html5.js"}

= javascript_include_tag('application_admin')

=# stylesheet_link_tag 'blueprint/print', :media => 'print'
=# stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'application_admin'

/[if lt IE 8]
  =# stylesheet_link_tag 'blueprint/ie'

app/views/admin/layouts/application.haml
!!!5
%html
  = render "admin/layouts/head"
  %body
    = render "admin/layouts/header"
    .container
      %section
        .admin_main_col
          = render "layouts/flash", flash: flash                      
          = yield
        .admin_side_col
          = render "admin/layouts/sidebar", sidebar_items: @sidebar, active: @sidebar_active
    =# render "admin/layouts/footer"
    = debug(params) if Rails.env.development?